# Generated by Django 5.0.7 on 2024-08-17 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name_plural': 'Тоdo'},
        ),
    ]
